### ISSUE TITLE
Fresh installation remarks

### ISSUE THREAD

**Issue by indyteo** [ignfab/building-roof-pipeline#3]
* Missing `python3-dev` for GDAL => `sudo apt install python3-dev`
* NumPy (and maybe Shapely) requirement needed by GDAL => should be installed before
* Probably a good idea to merge all the `apt install`s in the first step
* Needed `python3.10-venv` to use `python3 -m venv venv/roof`
* MPFR needs `makeinfo` command => `sudo apt install texinfo`
* Single install script maybe useful (with options to force download & install libs OR autodetect they are already installed with a satisfying version and skip them)
* Need clear failure messages (RED) and `exit` on fail (not always the case)

**Comment by esgn** [comment]
All points solved. Only point remaining is the single install script. Will be dealt with in the future.
